### ISSUE TITLE
Problem with generating DTO

### ISSUE THREAD

**Issue by jakubpas** [hanack/intellij-generator-plugin#15]
When I try to generate DTO I have:

`NoSuchMethodError: com.intellij.psi.PsiManager.getCodeStyleManager()Lcom/intellij/psi/codeStyle/CodeStyleManager;`

**Comment by l0co** [comment]
Still not fixed, plugin doesn't work in idea 2018.1
